### PR TITLE
Created projects for Visual Studio v17 (2022)

### PR DESCRIPTION
**Pull request by MajorMurphy**
Just adding the solution/project files to compile using the v143 platform toolset included with Visual Studio v17 (2022).

### CODE REVIEW

**Comment by MajorMurphy** [comment]
Master and v2.2.4 branches seem to be missing a referenced project in Tools/CmdLine/iccV5DspObsToV4Dsp

**Comment by maxderhak** [comment]
Sorry, My Bad.

**Comment by MajorMurphy** [comment]
ok, got it, and created a VS2022 solution for iccV5DspObsToV4Dsp

Doesn't affect this pull request, but FYI two other project files are missing:
- iccApplyProfiles_v16.vcxproj
- iccDumpProfile_v16.vcxproj

**Comment by maxderhak** [comment]
v16 projects added in.  Thanks for the help.

**Review by maxderhak — APPROVED** [review]

**Pull request merged**
