### PR TITLE
Bugfixes ar

### PR DESCRIPTION
**Pull request by art1pirat**
added some bugfixes and minor improvements:
- fixed nullpointer dereference in CIccCombinedConnectionConditions()
- fixed missed version check in readValidate()
- improved checkHeader() using compare_float()
- some additional minors

### CODE REVIEW

**Review by maxderhak — COMMENTED** [review]
It is correct that v2 profiles do not have a profile ID specified, so for the purposes of validation it is probably incorrect to indicate that it has a profile ID if the non-zero values don't match the calculated profile ID. A better approach would be to not check the version in line 798, but to add checks later that are specific to v2 to indicate that non-zero reserved data do or do not match calculated profile ID.

// Check profile ID
  if (Info.IsProfileIDCalculated(&m_Header.profileID)) {
    CalcProfileID(pIO, &profileID);
    if (memcmp((char*)profileID.ID8, (char*)m_Header.profileID.ID8, 16) != 0) {
      if (m_Header.version >= icVersionNumberV4) {
        sReport += icMsgValidateNonCompliant;
        sReport += "Bad Profile ID\r\n";

        rv = icMaxStatus(rv, icValidateNonCompliant);
      }
      else {
        sReport += icMsgValidateNonCompliant;
        sReport += "Version 2 profile has non-zero reserved data that doesn't match calculated Profile ID\r\n";

        rv = icMaxStatus(rv, icValidateNonCompliant);
      }
    }
    else if (m_Header.version < icVersionNumberV4) {
      sReport += icMsgValidateNonCompliant;
      sReport += "Version 2 profile has non-zero reserved data that matches calculated Profile ID\r\n";

      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
  }

**Review by maxderhak — APPROVED** [review]

**Review by maxderhak — CHANGES_REQUESTED** [review]
"if (i->ptr)" is not equivalent to "if (NULL == i->ptr)" rather it is equivalent to "if (i->ptr != NULL)"

**Review by maxderhak — APPROVED** [review]

**Comment by art1pirat** [comment]
> "if (i->ptr)" is not equivalent to "if (NULL == i->ptr)" rather it is equivalent to "if (i->ptr != NULL)"

Thanks. Will fix it.

**Comment by art1pirat** [comment]
> 



> It is correct that v2 profiles do not have a profile ID specified, so for the purposes of validation it is probably incorrect to indicate that it has a profile ID if the non-zero values don't match the calculated profile ID. A better approach would be to not check the version in line 798, but to add checks later that are specific to v2 to indicate that non-zero reserved data do or do not match calculated profile ID.
> 
> // Check profile ID if (Info.IsProfileIDCalculated(&m_Header.profileID)) { CalcProfileID(pIO, &profileID); if (memcmp((char*)profileID.ID8, (char*)m_Header.profileID.ID8, 16) != 0) { if (m_Header.version >= icVersionNumberV4) { sReport += icMsgValidateNonCompliant; sReport += "Bad Profile ID\r\n";
> 
> ```
>     rv = icMaxStatus(rv, icValidateNonCompliant);
>   }
>   else {
>     sReport += icMsgValidateNonCompliant;
>     sReport += "Version 2 profile has non-zero reserved data that doesn't match calculated Profile ID\r\n";
> 
>     rv = icMaxStatus(rv, icValidateNonCompliant);
>   }
> }
> else if (m_Header.version < icVersionNumberV4) {
>   sReport += icMsgValidateNonCompliant;
>   sReport += "Version 2 profile has non-zero reserved data that matches calculated Profile ID\r\n";
> 
>   rv = icMaxStatus(rv, icValidateNonCompliant);
> }
> ```
> 
> }

I would disagree with you. In v2.x.y the bytes are marked as reserved, but it is not required that they are filled with 0. Therefore, I would not test the ProfileID until v4.x.y. The validator could give the hint that the ProfileID would be possible for v2.x.y profiles, but this should then only be of informative character, instead of a warning or even an error message (see also Issue https://github.com/InternationalColorConsortium/DemoIccMAX/issues/44). Or did I just not understand you correctly?

**Comment by jens-st** [comment]
Merging this bugfix would help us better evaluate and validate old scanner and camera profiles (embedded in images of past digitisation projects). :+1:

**Review by maxderhak — COMMENTED** [review]
It might also be good to not send a warning when bytes 84..89 match the calculated profileID.

**Comment by art1pirat** [comment]
I will adapt your suggestions. It just takes a little bit of time.

**Comment by art1pirat** [comment]
I added your hints and extended it with comments to increase readability. I'm done and would appreciate the changes being incorporated into the main branch as soon as possible.

**Review by maxderhak — APPROVED** [review]

**Pull request merged**
