### PR TITLE
Fix wxstring conversion and include issues

### PR DESCRIPTION
**Pull request by maxderhak**

### CODE REVIEW

**Comment by maxderhak** [comment]
further work to fix dependency on nlohmann json for moder c++ is still needed for cmak builds.  The following might be helpful (beyond me). https://github.com/nlohmann/json?tab=readme-ov-file#integration

**Comment by xsscx** [comment]
@maxderhak 

Ok .. for  CMakeLists.txt, probably something like:

```
find_package(nlohmann_json REQUIRED)
target_link_libraries(iccApplyNamedCmm PRIVATE nlohmann_json::nlohmann_json)
target_link_libraries(iccApplyProfiles PRIVATE nlohmann_json::nlohmann_json)
```

I'll work on integration and return working CMakeLists.txt and anything else found. 

I'll check back 48 hours or less.

**Comment by xsscx** [comment]
# PR105 Build Script

The provided script for Linux will install deps, configure and make. Any errors are thrown to stdout.

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/xsscx/PatchIccMAX/refs/heads/development/contrib/UnitTest/pr105.sh)"
```

Time: Fri Nov 22 20:08:10 EST 2024

**Review by xsscx — CHANGES_REQUESTED** [review]
# PR105

The issues is that the missing CIccCfgDataApply functions and constructors are defined in IccCmmConfig.cpp, which is located in ./Tools/CmdLine/IccCommon/. However, this file is not being included in the build process for the iccApplyNamedCmm or iccApplyProfiles targets, leading to the undefined reference errors.

```
 find . -type f -name "*.h" | xargs grep -i "class CIccCfg"
./Tools/CmdLine/IccCommon/IccCmmConfig.h:class CIccCfgDataApply
./Tools/CmdLine/IccCommon/IccCmmConfig.h:class CIccCfgImageApply
./Tools/CmdLine/IccCommon/IccCmmConfig.h:class CIccCfgCreateLink
./Tools/CmdLine/IccCommon/IccCmmConfig.h:class CIccCfgProfile
./Tools/CmdLine/IccCommon/IccCmmConfig.h:class CIccCfgProfileSequence
./Tools/CmdLine/IccCommon/IccCmmConfig.h:class CIccCfgDataEntry
./Tools/CmdLine/IccCommon/IccCmmConfig.h:class CIccCfgColorData
```
For  CMakeLists.txt, probably something like:

```
find_package(nlohmann_json REQUIRED)
target_link_libraries(iccApplyNamedCmm PRIVATE nlohmann_json::nlohmann_json)
target_link_libraries(iccApplyProfiles PRIVATE nlohmann_json::nlohmann_json)
```

I'll work on integration and return working CMakeLists.txt and anything else found. 

I'll check back 48 hours or less.

## Build Errors

```
/usr/bin/ld: /usr/bin/ld: CMakeFiles/iccApplyNamedCmm.dir/home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp.o: in function `main':
/home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:242:(.text+0x9d5): undefined reference to `CIccCfgDataApply::CIccCfgDataApply()'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:243:(.text+0x9ef): undefined reference to `CIccCfgProfileSequence::CIccCfgProfileSequence()'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:244:(.text+0xa14): undefined reference to `CIccCfgColorData::CIccCfgColorData()'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:248:(.text+0xc2f): undefined reference to `loadJsonFrom(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>&, char const*)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:253:(.text+0xf44): undefined reference to `CIccCfgDataApply::fromJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:258:(.text+0x12d1): undefined reference to `CIccCfgProfileSequence::fromJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:265:(.text+0x1698): undefined reference to `CIccCfgColorData::fromJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:271:(.text+0x1856): undefined reference to `loadJsonFrom(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>&, char const*)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:271:(.text+0x1945): undefined reference to `CIccCfgColorData::fromJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:289:(.text+0x1e3c): undefined reference to `CIccCfgDataApply::fromArgs(char const**, int, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:297:(.text+0x2036): undefined reference to `CIccCfgProfileSequence::fromArgs(char const**, int, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:303:(.text+0x21ee): undefined reference to `CIccCfgColorData::fromLegacy(char const*, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:435:(.text+0x5c4b): undefined reference to `CIccCfgColorData::CIccCfgColorData()'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:462:(.text+0x62fb): undefined reference to `CIccCfgDataEntry::CIccCfgDataEntry()'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:579:(.text+0x8cfc): undefined reference to `CIccCfgColorData::toLegacy(char const*, CIccCfgProfileSequence*, unsigned char, unsigned char, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:584:(.text+0x8e7a): undefined reference to `CIccCfgProfileSequence::toJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>&) const'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:589:(.text+0x902a): undefined reference to `CIccCfgColorData::toJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>&) const'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:594:(.text+0x918d): undefined reference to `saveJsonAs(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void> const&, char const*, int)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:597:(.text+0x93db): undefined reference to `CIccCfgColorData::toIt8(char const*, unsigned char, unsigned char)'
CMakeFiles/iccApplyProfiles.dir/home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp.o: in function `main':
/home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:158:(.text+0x828): undefined reference to `CIccCfgImageApply::CIccCfgImageApply()'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:159:(.text+0x842): undefined reference to `CIccCfgProfileSequence::CIccCfgProfileSequence()'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:163:(.text+0xa5d): undefined reference to `loadJsonFrom(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>&, char const*)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:168:(.text+0xd5b): undefined reference to `CIccCfgImageApply::fromJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:173:(.text+0x10e8): undefined reference to `CIccCfgProfileSequence::fromJson(nlohmann::json_abi_v3_11_3::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::json_abi_v3_11_3::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> >, void>, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:182:(.text+0x1486): undefined reference to `CIccCfgImageApply::fromArgs(char const**, int, bool)'
/usr/bin/ld: /home/xss/tmp/DemoIccMAX/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:191:(.text+0x168a): undefined reference to `CIccCfgProfileSequence::fromArgs(char const**, int, bool)'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Tools/IccApplyNamedCmm/CMakeFiles/iccApplyNamedCmm.dir/build.make:98: Tools/IccApplyNamedCmm/iccApplyNamedCmm] Error 1
make[1]: *** [CMakeFiles/Makefile2:467: Tools/IccApplyNamedCmm/CMakeFiles/iccApplyNamedCmm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [Tools/IccApplyProfiles/CMakeFiles/iccApplyProfiles.dir/build.make:115: Tools/IccApplyProfiles/iccApplyProfiles] Error 1
```

**Comment by xsscx** [comment]
The windows build has the same errors because the missing CIccCfgDataApply functions and constructors are defined in IccCmmConfig.cpp, which is located in ./Tools/CmdLine/IccCommon/. However, this file is not being included in the build process for the iccApplyNamedCmm or iccApplyProfiles targets, leading to the undefined reference errors.

## Windows Example Reproduction

Requirment:

```
vcpkg integrate install
vcpkg install nlohmann-json libxml2:x64-windows tiff:x64-windows wxwidgets:x64-windows libxml2:x64-windows tiff:x64-windows wxwidgets:x64-windows libxml2:x64-windows-static tiff:x64-windows-static wxwidgets:x64-windows-static
```

```
[2024-11-22 21:24:54 E:\temp\DemoIccMAX]%  msbuild /m /maxcpucount "Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:AdditionalIncludeDirectories="C:\test\vcpkg\installed\x64-windows\include" /p:AdditionalLibraryDirectories="C:\test\vcpkg\installed\x64-windows-static\lib" /p:CLToolAdditionalOptions="/MT /Zi /Od /DDEBUG /W4" /p:LinkToolAdditionalOptions="/NODEFAULTLIB:msvcrt /LTCG /OPT:REF /INCREMENTAL:NO"
MSBuild version 17.12.6+db5f6012c for .NET Framework
Build started 11/22/2024 9:24:55 PM.

     1>Project "E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj" on node 1 (default targets).
     1>PrepareForBuild:
         Creating directory "x64\Release\".
         Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
         Creating directory "x64\Release\iccApplyNamedCmm.tlog\".
       InitializeBuildStatus:
         Creating "x64\Release\iccApplyNamedCmm.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
         Touching "x64\Release\iccApplyNamedCmm.tlog\unsuccessfulbuild".
       VcpkgTripletSelection:
         Using triplet "x64-windows" from "F:\test\vcpkg\installed\x64-windows\"
         Using normalized configuration "Release"
       ClCompile:
         C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\CL.exe /c /I..\..\..\IccProfLib /I"F:\test\vcpkg\installed\x64-windows\include" /Zi /nologo /W3 /WX- /diagnostics:column /O2 /Ob1 /D WIN32 /
         D NDEBUG /D _CONSOLE /D _VC80_UPGRADE=0x0710 /D _MBCS /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\Release/" /Fd"x64\Release/vc143.pdb" /external:W3 /Gd /TP /wd4996 /wd4996 /FC /errorReport:queue iccAp
         plyNamedCmm.cpp
         iccApplyNamedCmm.cpp
       Link:
         C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.42.34433\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:"x64\Release/iccApplyNamedCmm.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:..\..\..\IccProfLib\x64\Release /LIBPAT
         H:"F:\test\vcpkg\installed\x64-windows\lib" /LIBPATH:"F:\test\vcpkg\installed\x64-windows\lib\manual-link" IccProfLib.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib
         odbc32.lib odbccp32.lib "F:\test\vcpkg\installed\x64-windows\lib\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"x64\Release/iccApplyNamedCmm.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBAS
         E:NO /IMPLIB:"x64\Release\iccApplyNamedCmm.lib" /MACHINE:X64 x64\Release/iccApplyNamedCmm.obj
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "bool __cdecl saveJsonAs(class nlohmann::json_abi_v3_11_3::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_traits<char>,class std::all
       ocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_3::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void> const &,char const *,int)" (?saveJsonAs@@Y
       A_NAEBV?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@json_abi_v3_11_3@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@X@json_abi_v3_11_3@nlohmann@@PEBDH@Z) referen
       ced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "bool __cdecl loadJsonFrom(class nlohmann::json_abi_v3_11_3::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_traits<char>,class std::a
       llocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_3::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void> &,char const *)" (?loadJsonFrom@@YA_NAEA
       V?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@json_abi_v3_11_3@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@X@json_abi_v3_11_3@nlohmann@@PEBD@Z) referenced in
       function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: __cdecl CIccCfgDataApply::CIccCfgDataApply(void)" (??0CIccCfgDataApply@@QEAA@XZ) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccAppl
       yNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: int __cdecl CIccCfgDataApply::fromArgs(char const * *,int,bool)" (?fromArgs@CIccCfgDataApply@@QEAAHPEAPEBDH_N@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\
       CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: bool __cdecl CIccCfgDataApply::fromJson(class nlohmann::json_abi_v3_11_3::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_tra
       its<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_3::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void>,bool)" (?fromJson@
       CIccCfgDataApply@@QEAA_NV?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@json_abi_v3_11_3@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@X@json_abi_v3_11_3@nlohmann
       @@_N@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: __cdecl CIccCfgProfileSequence::CIccCfgProfileSequence(void)" (??0CIccCfgProfileSequence@@QEAA@XZ) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApp
       lyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: int __cdecl CIccCfgProfileSequence::fromArgs(char const * *,int,bool)" (?fromArgs@CIccCfgProfileSequence@@QEAAHPEAPEBDH_N@Z) referenced in function main [E:\temp\DemoI
       ccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: bool __cdecl CIccCfgProfileSequence::fromJson(class nlohmann::json_abi_v3_11_3::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::ch
       ar_traits<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_3::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void>,bool)" (?fro
       mJson@CIccCfgProfileSequence@@QEAA_NV?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@json_abi_v3_11_3@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@X@json_abi_v3_1
       1_3@nlohmann@@_N@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: void __cdecl CIccCfgProfileSequence::toJson(class nlohmann::json_abi_v3_11_3::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char
       _traits<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_3::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void> &)const " (?to
       Json@CIccCfgProfileSequence@@QEBAXAEAV?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@json_abi_v3_11_3@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@X@json_abi_v3_
       11_3@nlohmann@@@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: __cdecl CIccCfgDataEntry::CIccCfgDataEntry(void)" (??0CIccCfgDataEntry@@QEAA@XZ) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccAppl
       yNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: __cdecl CIccCfgColorData::CIccCfgColorData(void)" (??0CIccCfgColorData@@QEAA@XZ) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccAppl
       yNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: bool __cdecl CIccCfgColorData::fromLegacy(char const *,bool)" (?fromLegacy@CIccCfgColorData@@QEAA_NPEBD_N@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdL
       ine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: bool __cdecl CIccCfgColorData::fromJson(class nlohmann::json_abi_v3_11_3::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_tra
       its<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_3::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void>,bool)" (?fromJson@
       CIccCfgColorData@@QEAA_NV?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@json_abi_v3_11_3@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@X@json_abi_v3_11_3@nlohmann
       @@_N@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: bool __cdecl CIccCfgColorData::toLegacy(char const *,class CIccCfgProfileSequence *,unsigned char,unsigned char,bool)" (?toLegacy@CIccCfgColorData@@QEAA_NPEBDPEAVCIccC
       fgProfileSequence@@EE_N@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: bool __cdecl CIccCfgColorData::toIt8(char const *,unsigned char,unsigned char)" (?toIt8@CIccCfgColorData@@QEAA_NPEBDEE@Z) referenced in function main [E:\temp\DemoIccM
       AX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>iccApplyNamedCmm.obj : error LNK2019: unresolved external symbol "public: void __cdecl CIccCfgColorData::toJson(class nlohmann::json_abi_v3_11_3::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_trait
       s<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_3::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void> &)const " (?toJson@C
       IccCfgColorData@@QEBAXAEAV?$basic_json@Vmap@std@@Vvector@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@_N_J_KNVallocator@2@Uadl_serializer@json_abi_v3_11_3@nlohmann@@V?$vector@EV?$allocator@E@std@@@2@X@json_abi_v3_11_3@nlohman
       n@@@Z) referenced in function main [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>x64\Release\iccApplyNamedCmm.exe : fatal error LNK1120: 16 unresolved externals [E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj]
     1>Done Building Project "E:\temp\DemoIccMAX\Tools\CmdLine\IccApplyNamedCmm\iccApplyNamedCmm_v22.vcxproj" (default targets) -- FAILED.

Build FAILED.
```

**Comment by xsscx** [comment]
## Fixups for JSON Integration

Based on PR-107 there were changes needed to compile these projects, see PR https://github.com/InternationalColorConsortium/DemoIccMAX/pull/108

Source: https://github.com/xsscx/PatchIccMAX/tree/json-patches

```
	modified:   Readme.md
	new file:   Tools/CmdLine/IccApplyNamedCmm/CMakeLists.txt
	new file:   Tools/CmdLine/IccApplyProfiles/CMakeLists.txt
	modified:   Tools/CmdLine/IccCommon/IccCmmConfig.h
	modified:   Tools/CmdLine/IccCommon/IccJsonUtil.cpp
	modified:   Tools/CmdLine/IccCommon/IccJsonUtil.h
```

These changes verify that the subprojects IccApplyNamedCmm and IccApplyProfiles will compile to binary form and Link properly.


### Build Tools/CmdLine/IccApplyNamedCmm

```
cd Tools/CmdLine/IccApplyNamedCmm
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release . && make -j10  VERBOSE=1
```

#### Result

```
./iccApplyNamedCmm
iccApplyNamedCmm built with IccProfLib version 2.2.5
```

### Build Tools/CmdLine/IccApplyProfiles

```
cd Tools/CmdLine/IccApplyProfiles
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release . 
make VERBOSE=1
```

#### Result

```
 ./iccApplyProfiles
iccApplyProfiles built with IccProfLib version 2.2.5
```

## TODO
Next step is to integrate into top-level CMakeLists.txt

Please Merge the PR on PCS_Refactor then Merge into PR-107

**Comment by xsscx** [comment]
Once PR107 https://github.com/InternationalColorConsortium/DemoIccMAX/pull/107 gets Merged..

## TODO @xsscx 

- Documentation Updates
  - Top level Readme.md refreshed with dependency instructions

- Script Updates
  - Refactor the Build Code
 
- Ubuntu
  - Will need Path Added to CMakeLists.txt depending on flavor 

- Windows
  - Will need Path, vcpkg, choco refresh

- macOS arm64 reproduction
  - Will need Path Added to CMakeLists.txt

- Runners
  - Update the Azure & Github CI/CD's

**Review by xsscx — APPROVED** [review]
Confirmed Working 2024-11-23 23:06:48

**Pull request merged**
